
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wisnu
 */
public class daftar extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public daftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formDaftarJP = new javax.swing.JPanel();
        daftarHl = new javax.swing.JLabel();
        namaL = new javax.swing.JLabel();
        usmL = new javax.swing.JLabel();
        passL = new javax.swing.JLabel();
        emailL = new javax.swing.JLabel();
        noHpL = new javax.swing.JLabel();
        alamatL = new javax.swing.JLabel();
        daftarBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        passTF = new javax.swing.JPasswordField();
        namaTF = new javax.swing.JTextField();
        usmTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        noHpTF = new javax.swing.JTextField();
        rePassTF = new javax.swing.JPasswordField();
        repassL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTF = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daftar");

        formDaftarJP.setBackground(new java.awt.Color(20, 34, 73));

        daftarHl.setBackground(new java.awt.Color(255, 255, 255));
        daftarHl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        daftarHl.setForeground(new java.awt.Color(255, 255, 255));
        daftarHl.setText("Daftar");

        namaL.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        namaL.setForeground(new java.awt.Color(255, 255, 255));
        namaL.setText("Nama");

        usmL.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        usmL.setForeground(new java.awt.Color(255, 255, 255));
        usmL.setText("Nama Pengguna");

        passL.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        passL.setForeground(new java.awt.Color(255, 255, 255));
        passL.setText("Kata Sandi");

        emailL.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        emailL.setForeground(new java.awt.Color(255, 255, 255));
        emailL.setText("Email");

        noHpL.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        noHpL.setForeground(new java.awt.Color(255, 255, 255));
        noHpL.setText("Nomor HP");

        alamatL.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        alamatL.setForeground(new java.awt.Color(255, 255, 255));
        alamatL.setText("Alamat");

        daftarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        daftarBtn.setText("Daftar");
        daftarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBtnActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Punya Akun ?");

        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Masuk");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });

        noHpTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noHpTFKeyTyped(evt);
            }
        });

        repassL.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        repassL.setForeground(new java.awt.Color(255, 255, 255));
        repassL.setText("Ulangi Kata Sandi");

        alamatTF.setColumns(20);
        alamatTF.setRows(5);
        jScrollPane1.setViewportView(alamatTF);

        javax.swing.GroupLayout formDaftarJPLayout = new javax.swing.GroupLayout(formDaftarJP);
        formDaftarJP.setLayout(formDaftarJPLayout);
        formDaftarJPLayout.setHorizontalGroup(
            formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formDaftarJPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(daftarHl)
                .addGap(136, 136, 136))
            .addGroup(formDaftarJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formDaftarJPLayout.createSequentialGroup()
                        .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaL)
                            .addComponent(usmL)
                            .addComponent(passL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usmTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(formDaftarJPLayout.createSequentialGroup()
                            .addComponent(repassL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rePassTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(formDaftarJPLayout.createSequentialGroup()
                            .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(formDaftarJPLayout.createSequentialGroup()
                                    .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(noHpL)
                                        .addComponent(alamatL))
                                    .addGap(73, 73, 73))
                                .addComponent(emailL, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(formDaftarJPLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(noHpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formDaftarJPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formDaftarJPLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginBtn))
                            .addComponent(daftarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        formDaftarJPLayout.setVerticalGroup(
            formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDaftarJPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(daftarHl)
                .addGap(21, 21, 21)
                .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaL)
                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usmL)
                    .addComponent(usmTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passL)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rePassTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repassL))
                .addGap(18, 18, 18)
                .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailL))
                .addGap(22, 22, 22)
                .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noHpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noHpL))
                .addGap(30, 30, 30)
                .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formDaftarJPLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(daftarBtn)
                        .addGap(18, 18, 18)
                        .addGroup(formDaftarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginBtn)
                            .addComponent(jLabel9))
                        .addGap(7, 7, 7))
                    .addGroup(formDaftarJPLayout.createSequentialGroup()
                        .addComponent(alamatL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(formDaftarJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDaftarJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String vpassword,vmd5,vsha1;
    private String encryptPasswordSHA1(String password){
        vpassword= password;
        String encPass=null;
        try{
            MessageDigest digest=MessageDigest.getInstance("SHA1");
           digest.update(vpassword.getBytes(),0,vpassword.length());
           encPass=new BigInteger(1,digest.digest()).toString(16);
           vsha1=encPass.toUpperCase();
        }
        catch(Exception e){
           e.printStackTrace();
        }
           return vsha1;
    }
    
    private void daftarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBtnActionPerformed
        // TODO add your handling code here:
        String level = "user";
        try {
            if (namaTF.getText().equals("") || usmTF.getText().equals("") || 
                passTF.getText().equals("") || alamatTF.getText().equals("") || 
                noHpTF.getText().equals("") || emailTF.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Form harus diisi dengan "
                    + "lengkap");
                resetForm();
            } else {
                if (passTF.getText().equalsIgnoreCase(rePassTF.getText())) {
                    Pattern ptn = Pattern.compile("^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$");
                    Matcher matcher = ptn.matcher(emailTF.getText());
                    if(matcher.matches()){
                        String cekEmail = "SELECT email FROM user WHERE email = '"+emailTF.getText()+"'";
                        java.sql.Connection conn = ((Connection) Config.configDB());
                        java.sql.Statement stm = conn.createStatement();
                        java.sql.ResultSet res = stm.executeQuery(cekEmail);
                        String cekNoHp = "SELECT noHP FROM user WHERE noHP = '"+noHpTF.getText()+"'";
                        java.sql.Statement stm2 = conn.createStatement();
                        java.sql.ResultSet res2 = stm2.executeQuery(cekNoHp);
                        res.next();                              
                        res2.next();                              
                        res.last();                              
                        res2.last();                              
                        if (res.getRow() == 1) {
                            JOptionPane.showMessageDialog(this, "Email sudah digunakan" );
                        } else if (res2.getRow() == 1) {
                            JOptionPane.showMessageDialog(this, "Nomor Handphone sudah digunakan" );
                        } else {
                            String sql = "INSERT INTO user VALUES "
                                + "('"+namaTF.getText()+"','"+usmTF.getText()+"','"
                                +encryptPasswordSHA1(passTF.getText())+"','"+level+"','"+alamatTF.getText()+"','"
                                +noHpTF.getText()+"','"+emailTF.getText()+"')";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                            JOptionPane.showMessageDialog(null, "Berhasil Register");
                            this.dispose();
                            new masuk().setVisible(true);
                        }                                                                       
                    } else {
                        JOptionPane.showMessageDialog(this, "Format email salah" );
                    }                    
                } else {
                    JOptionPane.showMessageDialog(this, "Kata sandi tidak cocok");
                }                
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Username sudah digunakan");
        }
    }//GEN-LAST:event_daftarBtnActionPerformed

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new masuk().setVisible(true);
    }//GEN-LAST:event_loginBtnMouseClicked

    private void noHpTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noHpTFKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_noHpTFKeyTyped

    public void resetForm() {
        namaTF.setText("");
        usmTF.setText("");
        passTF.setText("");
        alamatTF.setText("");
        noHpTF.setText("");
        emailTF.setText("");
        rePassTF.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatL;
    private javax.swing.JTextArea alamatTF;
    private javax.swing.JButton daftarBtn;
    private javax.swing.JLabel daftarHl;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JPanel formDaftarJP;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel namaL;
    private javax.swing.JTextField namaTF;
    private javax.swing.JLabel noHpL;
    private javax.swing.JTextField noHpTF;
    private javax.swing.JLabel passL;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JPasswordField rePassTF;
    private javax.swing.JLabel repassL;
    private javax.swing.JLabel usmL;
    private javax.swing.JTextField usmTF;
    // End of variables declaration//GEN-END:variables
}
