
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FileOutputStream;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.*;
import com.itextpdf.text.Document;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nur Muhammad Luthfi
 */
public class InvoiceNew extends javax.swing.JFrame {
    String idT = Tiket.getIdTiket();
    String nama = User.getNama();
    String s;
    /**
     * Creates new form InvoiceNew
     */
    public InvoiceNew() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        konfirmBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        namaL = new javax.swing.JLabel();
        artisL = new javax.swing.JLabel();
        jadwalL = new javax.swing.JLabel();
        jmlTiketL = new javax.swing.JLabel();
        totBayarL = new javax.swing.JLabel();
        noRekL = new javax.swing.JLabel();
        statusL = new javax.swing.JLabel();
        unggahBuktiBtn = new javax.swing.JButton();
        fotoL = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invoice");

        jPanel1.setBackground(new java.awt.Color(20, 34, 73));

        jPanel3.setBackground(new java.awt.Color(20, 34, 73));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGap(205, 205, 205))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jLabel3.setText("Invoice");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nama ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Silahkan Transfer Ke");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Status Pembayaran");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total Pembayaran");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Jumlah Tiket");

        konfirmBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        konfirmBtn.setText("Konfirmasi Pembayaran");
        konfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Artis");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jadwal Konser");

        noRekL.setText("Mandiri: 101-000-06344132-3 A/n Nur Muhammad Luthfi");

        unggahBuktiBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unggahBuktiBtn.setText("Unggah Bukti Pembayaran");
        unggahBuktiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unggahBuktiBtnActionPerformed(evt);
            }
        });

        fotoL.setMaximumSize(new java.awt.Dimension(300, 300));
        fotoL.setMinimumSize(new java.awt.Dimension(300, 300));
        fotoL.setPreferredSize(new java.awt.Dimension(300, 300));

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        printBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printBtn.setText("Cetak Nota");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(namaL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(artisL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jadwalL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jmlTiketL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totBayarL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noRekL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fotoL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(konfirmBtn)
                                            .addComponent(unggahBuktiBtn))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(printBtn)
                                            .addComponent(backBtn))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(namaL))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(artisL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jadwalL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jmlTiketL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(totBayarL))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(noRekL))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(statusL))
                .addGap(2, 2, 2)
                .addComponent(fotoL, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unggahBuktiBtn)
                    .addComponent(printBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konfirmBtn)
                    .addComponent(backBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void konfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmBtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM tiket NATURAL JOIN membeli WHERE idTiket = '"+idT+"' ORDER BY idBeli DESC LIMIT 1";
            java.sql.Connection conn = ((Connection) Config.configDB());
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            if(res.next()) {
//                int kuota = Integer.parseInt(res.getString("kuota"));
//                String jumlahTIket = jmlTiketL.getText();
//                int jumlahBeli = Integer.parseInt(jumlahTIket);
//                kuota = kuota - jumlahBeli;
//                String kurangiKuota = "UPDATE tiket SET kuota = '"+kuota+"' WHERE idTiket = '"+idT+"'";
//                java.sql.PreparedStatement pst = conn.prepareStatement(kurangiKuota);
//                pst.execute();
                InputStream is = new FileInputStream(new File(s));
                String konfirm = "UPDATE membeli SET buktiTF = ? WHERE idBeli = '"+res.getString("idBeli")+"'";
                java.sql.PreparedStatement pst2 = conn.prepareStatement(konfirm);
                pst2.setBinaryStream(1, is);
                pst2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil Menggungah Bukti Pembelian");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_konfirmBtnActionPerformed

    private void unggahBuktiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unggahBuktiBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            fotoL.setIcon(ResizeImage(path));
            s = path;
        } else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No Data");
        }
    }//GEN-LAST:event_unggahBuktiBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ListEvent().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM membeli NATURAL JOIN tiket WHERE idBeli = '"+Membeli.getIdMembeli()+"' AND username = '"+User.getUsername()+"' AND idTiket = '"+idT+"'";
            java.sql.Connection conn = ((Connection) Config.configDB());
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            if(res.next()) {
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream("Invoice " + res.getString("idBeli") + ".pdf"));
                document.open();
                document.add(new Paragraph("idBeli: " + res.getString("idbeli")));
                document.add(new Paragraph("Nama: " + nama));
                document.add(new Paragraph("Artis: " + res.getString("artis")));
                document.add(new Paragraph("Jadwal Konser: " + res.getString("tanggal") + " Pukul: " + res.getString("pukul")));            
                document.add(new Paragraph("Jumlah Tiket: " + res.getString("jumlahBeli")));
                int harga = Integer.parseInt(res.getString("harga"));
                int jumlahTiket = res.getShort("jumlahBeli");
                int jumlahBayar = harga * jumlahTiket;
                String jmlhBayar = Integer.toString(jumlahBayar);
                document.add(new Paragraph("Total Pembayaran: " + jmlhBayar));
                document.add(new Paragraph("Status Pembayaran: " + res.getString("statusPembelian")));
                document.close();
                JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Berkas");
            }           
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_printBtnActionPerformed
    
    public void loadData() {
        try {
            namaL.setText(nama);            
            String sql = "SELECT * FROM membeli NATURAL JOIN tiket WHERE idBeli = '"+Membeli.getIdMembeli()+"' AND username = '"+User.getUsername()+"' AND idTiket = '"+idT+"'";
            java.sql.Connection conn = ((Connection) Config.configDB());
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            if(res.next()) {
                artisL.setText(res.getString("artis"));
                jmlTiketL.setText(Integer.toString(res.getShort("jumlahBeli")));
                jadwalL.setText("Tanggal: " + res.getString("tanggal") + " Pukul: " + res.getString("pukul"));
                int harga = Integer.parseInt(res.getString("harga"));
                int jumlahTiket = res.getShort("jumlahBeli");
                int jumlahBayar = harga * jumlahTiket;
                String jmlhBayar = Integer.toString(jumlahBayar);
                totBayarL.setText(jmlhBayar);
                statusL.setText(res.getString("statusPembelian"));
                byte [] img = res.getBytes("buktiTF");  
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(300, 300,Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(myImg);
                fotoL.setIcon(icon);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(fotoL.getWidth(), fotoL.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artisL;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel fotoL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jadwalL;
    private javax.swing.JLabel jmlTiketL;
    private javax.swing.JButton konfirmBtn;
    private javax.swing.JLabel namaL;
    private javax.swing.JLabel noRekL;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel statusL;
    private javax.swing.JLabel totBayarL;
    private javax.swing.JButton unggahBuktiBtn;
    // End of variables declaration//GEN-END:variables
}
