
import java.sql.Connection;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.Blob;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nur Muhammad Luthfi
 */
public class LearnMore extends javax.swing.JFrame {

    /**
     * Creates new form LearnMore
     */
    String idT = Tiket.getIdTiket();
    
    public LearnMore() {
        initComponents();
        usernameL.setText(User.getUsername());
        shImg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeHl = new javax.swing.JLabel();
        navJP = new javax.swing.JPanel();
        usernameL = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        konselL = new javax.swing.JLabel();
        infoTiketPnl = new javax.swing.JPanel();
        artisL = new javax.swing.JLabel();
        temaL = new javax.swing.JLabel();
        lokasiL = new javax.swing.JLabel();
        tglL = new javax.swing.JLabel();
        pukukL = new javax.swing.JLabel();
        kuotaL = new javax.swing.JLabel();
        hargaL = new javax.swing.JLabel();
        beliBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskTa = new javax.swing.JTextArea();
        deskL = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        posterL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learn More");
        setPreferredSize(new java.awt.Dimension(740, 690));
        setSize(new java.awt.Dimension(1024, 720));

        homeHl.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        homeHl.setText("Discover Great Events");

        navJP.setBackground(new java.awt.Color(20, 34, 73));
        navJP.setPreferredSize(new java.awt.Dimension(725, 53));

        usernameL.setBackground(new java.awt.Color(255, 255, 255));
        usernameL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usernameL.setForeground(new java.awt.Color(255, 255, 255));
        usernameL.setText("username");
        usernameL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameLMouseClicked(evt);
            }
        });

        logo.setFont(new java.awt.Font("Yu Gothic Medium", 3, 16)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log.jpg"))); // NOI18N
        logo.setText("Tiketin");
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        konselL.setBackground(new java.awt.Color(255, 255, 255));
        konselL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        konselL.setForeground(new java.awt.Color(255, 255, 255));
        konselL.setText("Konser");

        javax.swing.GroupLayout navJPLayout = new javax.swing.GroupLayout(navJP);
        navJP.setLayout(navJPLayout);
        navJPLayout.setHorizontalGroup(
            navJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navJPLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(konselL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                .addComponent(usernameL)
                .addContainerGap())
        );
        navJPLayout.setVerticalGroup(
            navJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameL)
                    .addComponent(logo)
                    .addComponent(konselL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoTiketPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        artisL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        artisL.setText("Artis");

        temaL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        temaL.setText("Tema");

        lokasiL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lokasiL.setText("Lokasi");

        tglL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tglL.setText("Tanggal");

        pukukL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pukukL.setText("Pukul");

        kuotaL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kuotaL.setText("Kuota");

        hargaL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargaL.setText("Harga");

        beliBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        beliBtn.setText("Beli");
        beliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        deskTa.setColumns(20);
        deskTa.setRows(5);
        deskTa.setAutoscrolls(false);
        jScrollPane1.setViewportView(deskTa);

        deskL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deskL.setText("Deskripsi");

        javax.swing.GroupLayout infoTiketPnlLayout = new javax.swing.GroupLayout(infoTiketPnl);
        infoTiketPnl.setLayout(infoTiketPnlLayout);
        infoTiketPnlLayout.setHorizontalGroup(
            infoTiketPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTiketPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoTiketPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(artisL)
                    .addComponent(temaL)
                    .addComponent(lokasiL)
                    .addComponent(tglL)
                    .addComponent(pukukL)
                    .addComponent(kuotaL)
                    .addComponent(hargaL)
                    .addGroup(infoTiketPnlLayout.createSequentialGroup()
                        .addComponent(beliBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deskL))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        infoTiketPnlLayout.setVerticalGroup(
            infoTiketPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTiketPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(artisL)
                .addGap(18, 18, 18)
                .addComponent(temaL)
                .addGap(18, 18, 18)
                .addComponent(deskL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lokasiL)
                .addGap(18, 18, 18)
                .addComponent(tglL)
                .addGap(18, 18, 18)
                .addComponent(pukukL)
                .addGap(18, 18, 18)
                .addComponent(kuotaL)
                .addGap(18, 18, 18)
                .addComponent(hargaL)
                .addGap(27, 27, 27)
                .addGroup(infoTiketPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beliBtn)
                    .addComponent(backBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        footer.setBackground(new java.awt.Color(20, 34, 73));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Copyrigth Tiketin 2018");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeHl, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posterL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoTiketPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeHl)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoTiketPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posterL)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void beliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT kuota FROM tiket WHERE idTiket = '"+idT+"'";
            java.sql.Connection conn = ((Connection) Config.configDB());
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            int kuota = 0;
            if (res.next()) 
                 kuota = Integer.parseInt(res.getString("kuota"));
            if (kuota > 0 ){
                this.dispose();
                new pembayaran().setVisible(true);
            } else {
                 JOptionPane.showMessageDialog(null, "Kuota Penuh");
            }          
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Ada error"
            + e.getMessage());
        }
    }//GEN-LAST:event_beliBtnActionPerformed

    private void usernameLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameLMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new MenuUser().setVisible(true);
    }//GEN-LAST:event_usernameLMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_logoMouseClicked

    public void shImg() {
        try {
            String sql = "SELECT * FROM tiket WHERE idTiket = '"+idT+"'";
            java.sql.Connection conn = ((Connection) Config.configDB());
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            if (res.next()) {
                byte [] img = res.getBytes("poster");          
                artisL.setText("Artis: " + res.getString("artis"));
                temaL.setText("Tema: " + res.getString("tema"));
                tglL.setText("Tanggal: " + res.getString("tanggal"));
                lokasiL.setText("Lokasi: " + res.getString("lokasi"));
                pukukL.setText("Pukul: " + res.getString("pukul"));
                 hargaL.setText("harga: Rp" + res.getString("harga"));
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(300, 300,Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(myImg);
                posterL.setIcon(icon);      
                deskTa.setLineWrap(true);
                DefaultCaret caret = (DefaultCaret) deskTa.getCaret();
                caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
                deskTa.setText(res.getString("deskripsi"));
                int kuota = Integer.parseInt(res.getString("kuota"));
                if (kuota > 0 ){                    
                    kuotaL.setText("Kuota: " + res.getString("kuota") + " Orang");                   
                } else {
                    kuotaL.setText("Kuota penuh");
                }                                                          
            } else
                JOptionPane.showMessageDialog(null, "No Data");
        } catch(Exception e)  {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnMore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnMore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnMore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnMore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnMore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artisL;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton beliBtn;
    private javax.swing.JLabel deskL;
    private javax.swing.JTextArea deskTa;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel hargaL;
    private javax.swing.JLabel homeHl;
    private javax.swing.JPanel infoTiketPnl;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel konselL;
    private javax.swing.JLabel kuotaL;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel lokasiL;
    private javax.swing.JPanel navJP;
    private javax.swing.JLabel posterL;
    private javax.swing.JLabel pukukL;
    private javax.swing.JLabel temaL;
    private javax.swing.JLabel tglL;
    private javax.swing.JLabel usernameL;
    // End of variables declaration//GEN-END:variables
}
