
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nur Muhammad Luthfi
 */
public class ListEvent extends javax.swing.JFrame {

    String username = User.getUsername();
    public static int statusSearch = 0;
    /**
     * Creates new form ListEvent
     */
    public ListEvent() {
        initComponents();
        load_table();
        usmL.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navJP = new javax.swing.JPanel();
        searchTF = new javax.swing.JTextField();
        usmL = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        konselL = new javax.swing.JLabel();
        cariBtn = new javax.swing.JButton();
        homeSP = new javax.swing.JScrollPane();
        listTiketTbl = new javax.swing.JTable();
        homeHl = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        learnMoreBtn = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tiket Anda");

        navJP.setBackground(new java.awt.Color(20, 34, 73));

        searchTF.setText("Pencarian");

        usmL.setBackground(new java.awt.Color(255, 255, 255));
        usmL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usmL.setForeground(new java.awt.Color(255, 255, 255));
        usmL.setText("username");
        usmL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usmLMouseClicked(evt);
            }
        });

        logo.setFont(new java.awt.Font("Yu Gothic Medium", 3, 16)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log.jpg"))); // NOI18N
        logo.setText("Tiketin");
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        konselL.setBackground(new java.awt.Color(255, 255, 255));
        konselL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        konselL.setForeground(new java.awt.Color(255, 255, 255));
        konselL.setText("Konser");

        cariBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cariBtn.setText("Cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navJPLayout = new javax.swing.GroupLayout(navJP);
        navJP.setLayout(navJPLayout);
        navJPLayout.setHorizontalGroup(
            navJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navJPLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(konselL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usmL)
                .addGap(18, 18, 18)
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariBtn)
                .addContainerGap())
        );
        navJPLayout.setVerticalGroup(
            navJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usmL)
                    .addComponent(logo)
                    .addComponent(konselL)
                    .addComponent(cariBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listTiketTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID Beli", "ID Tikel", "Tema", "Artis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listTiketTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTiketTblMouseClicked(evt);
            }
        });
        homeSP.setViewportView(listTiketTbl);
        if (listTiketTbl.getColumnModel().getColumnCount() > 0) {
            listTiketTbl.getColumnModel().getColumn(1).setMinWidth(0);
            listTiketTbl.getColumnModel().getColumn(1).setPreferredWidth(0);
            listTiketTbl.getColumnModel().getColumn(1).setMaxWidth(0);
            listTiketTbl.getColumnModel().getColumn(2).setMinWidth(0);
            listTiketTbl.getColumnModel().getColumn(2).setPreferredWidth(0);
            listTiketTbl.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        homeHl.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        homeHl.setText("Tiket Anda");

        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshBtn.setText("Segarkan Tabel");
        refreshBtn.setToolTipText("");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        learnMoreBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        learnMoreBtn.setText("Pelajari Lebih Lanjut");
        learnMoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnMoreBtnActionPerformed(evt);
            }
        });

        footer.setBackground(new java.awt.Color(20, 34, 73));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Copyrigth Tiketin 2018");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setText("Kembali");
        backBtn.setToolTipText("");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeHl)
                .addGap(338, 338, 338))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeSP, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(learnMoreBtn)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn)
                        .addGap(18, 18, 18)
                        .addComponent(backBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeHl)
                .addGap(53, 53, 53)
                .addComponent(homeSP, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(learnMoreBtn)
                    .addComponent(refreshBtn)
                    .addComponent(backBtn))
                .addGap(18, 18, 18)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usmLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usmLMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new MenuUser().setVisible(true);
    }//GEN-LAST:event_usmLMouseClicked

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        // TODO add your handling code here:
        statusSearch = 1;
        if(searchTF.getText().isEmpty())
        statusSearch = 0;
        else if (statusSearch == 1) {
            DefaultTableModel model = (DefaultTableModel) listTiketTbl.getModel();
            String cari = searchTF.getText();
            try {
                int baris = listTiketTbl.getRowCount();
                for (int i = 0; i < baris; i++) {
                    model.removeRow(i);
                }
                int no = 1;
                String sql = "SELECT * FROM membeli NATURAL JOIN tiket WHERE artis LIKE '"+cari+"%'"
                + "OR tema LIKE '"+cari+"%' AND username = '"+username+"' ORDER BY idTiket";
                java.sql.Connection conn = ((Connection) Config.configDB());
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                while (res.next()) {
                    model.addRow(new Object[] {no++, res.getString("idTiket"),res.getString("tema"), res.getString("artis")});
                }
                listTiketTbl.setModel(model);
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(this, "Data yang dicari tidak ada !!!!");
            }
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void listTiketTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTiketTblMouseClicked
        // TODO add your handling code here:
        int selectedRow = listTiketTbl.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) listTiketTbl.getModel();
        Tiket.setIdTiket(model.getValueAt(selectedRow, 2).toString());
        Membeli.setIdMembeli(model.getValueAt(selectedRow, 1).toString());
    }//GEN-LAST:event_listTiketTblMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        load_table();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void learnMoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnMoreBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new InvoiceNew().setVisible(true);
    }//GEN-LAST:event_learnMoreBtnActionPerformed

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_logoMouseClicked

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuUser().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    public void load_table() {
        try {
            DefaultTableModel model = (DefaultTableModel) listTiketTbl.getModel();
            int baris = listTiketTbl.getRowCount();
                for (int i = 0; i < baris; i++) {
                    model.removeRow(i);
            }
            int no = 1;
            String sql = "SELECT * FROM tiket NATURAL JOIN membeli WHERE username = '"+username+"' ORDER BY idBeli";
            java.sql.Connection conn = ((Connection) Config.configDB());
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {                
                model.addRow(new Object[] {no++, res.getString("idBeli"), res.getString("idTiket"), res.getString("tema"), res.getString("artis")});
            }
            listTiketTbl.setModel(model);
        } catch(Exception e) {
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cariBtn;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel homeHl;
    private javax.swing.JScrollPane homeSP;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel konselL;
    private javax.swing.JButton learnMoreBtn;
    private javax.swing.JTable listTiketTbl;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel navJP;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField searchTF;
    private javax.swing.JLabel usmL;
    // End of variables declaration//GEN-END:variables
}
