
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wisnu
 */
public class masuk extends javax.swing.JFrame {

    /**
     * Creates new form cobaa
     */
    
    public masuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formMasukJPl = new javax.swing.JPanel();
        masukHl = new javax.swing.JLabel();
        masukBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        daftarBtn = new javax.swing.JLabel();
        usmL = new javax.swing.JLabel();
        passL = new javax.swing.JLabel();
        usmTF = new javax.swing.JTextField();
        passTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Masuk");
        setBackground(new java.awt.Color(20, 34, 73));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(20, 34, 73));

        masukHl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        masukHl.setText("Masuk");

        masukBtn.setBackground(new java.awt.Color(255, 255, 255));
        masukBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masukBtn.setText("Masuk");
        masukBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Belum Punya Akun ?");

        daftarBtn.setBackground(new java.awt.Color(0, 0, 204));
        daftarBtn.setForeground(new java.awt.Color(51, 0, 153));
        daftarBtn.setText("Daftar ");
        daftarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarBtnMouseClicked(evt);
            }
        });

        usmL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usmL.setText("Nama Pengguna");

        passL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passL.setText("Kata Sandi");

        javax.swing.GroupLayout formMasukJPlLayout = new javax.swing.GroupLayout(formMasukJPl);
        formMasukJPl.setLayout(formMasukJPlLayout);
        formMasukJPlLayout.setHorizontalGroup(
            formMasukJPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formMasukJPlLayout.createSequentialGroup()
                .addGroup(formMasukJPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formMasukJPlLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(formMasukJPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usmL)
                            .addComponent(passL))
                        .addGroup(formMasukJPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(formMasukJPlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(daftarBtn)
                                .addGap(117, 117, 117))
                            .addGroup(formMasukJPlLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(formMasukJPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(masukBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(formMasukJPlLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(masukHl)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        formMasukJPlLayout.setVerticalGroup(
            formMasukJPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formMasukJPlLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(masukHl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(formMasukJPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usmL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formMasukJPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passL)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(masukBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formMasukJPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daftarBtn)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(formMasukJPl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(formMasukJPl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new daftar().setVisible(true);
    }//GEN-LAST:event_daftarBtnMouseClicked
    
    String vpassword,vmd5,vsha1;
    private String encryptPasswordSHA1(String password){
        vpassword= password;
        String encPass=null;
        try{
            MessageDigest digest=MessageDigest.getInstance("SHA1");
           digest.update(vpassword.getBytes(),0,vpassword.length());
           encPass=new BigInteger(1,digest.digest()).toString(16);
           vsha1=encPass.toUpperCase();
        }
        catch(Exception e){
           e.printStackTrace();
        }
           return vsha1;
    }
    
    private void masukBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukBtnActionPerformed
        // TODO add your handling code here:
        try {
            if (usmTF.getText().equals("") || passTF.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Form harus diisi dengan "
                    + "Lengkap");
                resetForm();
            } else {
                String sql = "SELECT * FROM user WHERE username = "
                        + "'"+usmTF.getText()+ "' AND password = '" +encryptPasswordSHA1(passTF.getText())+ "'";
                java.sql.Connection conn = ((Connection) Config.configDB());
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                while (res.next()) {                    
                    if(res.getRow() == 1) {
                        User.setUsername(usmTF.getText());
                        User.setNama(res.getString("nama"));
                        if (res.getString("level").equalsIgnoreCase("admin")) {
                            JOptionPane.showMessageDialog(null, "Selamat Datang "
                                + res.getString("nama"));
                            this.dispose();
                            new MenuAdmin().setVisible(true);
                        } else if (res.getString("level").equalsIgnoreCase("user")){
                            JOptionPane.showMessageDialog(null, "Selamat Datang "
                                + res.getString("nama"));
                            this.dispose();
                            new home().setVisible(true);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Maaf nama pengguna atau"
                            + " password salah");
                        resetForm();
                    }
                }                
            }                           
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            resetForm();
        }
    }//GEN-LAST:event_masukBtnActionPerformed

    public void resetForm() {
        usmTF.setText("");
        passTF.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftarBtn;
    private javax.swing.JPanel formMasukJPl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton masukBtn;
    private javax.swing.JLabel masukHl;
    private javax.swing.JLabel passL;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JLabel usmL;
    private javax.swing.JTextField usmTF;
    // End of variables declaration//GEN-END:variables
}
